/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppContainerMain: typeof import('./src/components/app-container/main.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconsIconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
